.pragma library

// Theme texts, translated into 12 languages.
// Every text shown by the theme is here (Windows 11 wording).
// The language follows the system language, with English as fallback.
// The \n are intended line breaks (tooltips do not wrap by themselves).

var texts = {
    "en": {
        welcome: "Welcome",
        onScreenKeyboard: "On-screen keyboard",
        accessibility: "Accessibility",
        on: "On",
        off: "Off",
        powerOptions: "Power options",
        shutdownDesc: "Closes all apps\nand turns off the PC.",
        restartDesc: "Closes all apps, turns off the PC,\nand then turns it on again.",
        sleepDesc: "The PC stays on but uses low power.\nApps stay open so when the PC wakes up,\nyou're instantly back to where you left off.",
        pin: "PIN",
        submit: "Submit",
        ok: "OK",
        wrongPassword: "The password is incorrect. Try again.",
        shutdown: "Shut down",
        restart: "Restart",
        sleep: "Sleep",
        password: "Password",
        capsLock: "Caps Lock is on",
        networkWired: "Connected (wired)",
        networkWifi: "Connected (Wi-Fi)",
        networkNone: "Not connected"
    },
    "fr": {
        welcome: "Bienvenue",
        onScreenKeyboard: "Clavier visuel",
        accessibility: "Accessibilité",
        on: "Activé",
        off: "Désactivé",
        powerOptions: "Options d'alimentation",
        shutdownDesc: "Ferme toutes les applications\net éteint le PC.",
        restartDesc: "Ferme toutes les applications,\néteint le PC, puis le rallume.",
        sleepDesc: "Le PC reste allumé mais consomme peu d'énergie.\nLes applications restent ouvertes; ainsi,\nlorsque le PC sort de veille, vous retrouvez instantanément\nvotre travail là où vous l'aviez laissé.",
        pin: "Code PIN",
        submit: "Envoyer",
        ok: "OK",
        wrongPassword: "Le mot de passe est incorrect. Réessayez.",
        shutdown: "Arrêt",
        restart: "Redémarrer",
        sleep: "Mettre en veille",
        password: "Mot de passe",
        capsLock: "Le verrouillage des majuscules est activé",
        networkWired: "Connecté (filaire)",
        networkWifi: "Connecté (Wi-Fi)",
        networkNone: "Aucune connexion"
    },
    "de": {
        welcome: "Willkommen",
        onScreenKeyboard: "Bildschirmtastatur",
        accessibility: "Barrierefreiheit",
        on: "Ein",
        off: "Aus",
        powerOptions: "Energieoptionen",
        shutdownDesc: "Schließt alle Apps und\nschaltet den PC aus.",
        restartDesc: "Schließt alle Apps, schaltet den PC aus\nund dann wieder ein.",
        sleepDesc: "Der PC bleibt eingeschaltet, verbraucht aber wenig Energie.\nApps bleiben geöffnet, sodass Sie beim Reaktivieren\ndes PCs sofort dort weitermachen, wo Sie aufgehört haben.",
        pin: "PIN",
        submit: "Senden",
        ok: "OK",
        wrongPassword: "Das Kennwort ist falsch. Versuchen Sie es erneut.",
        shutdown: "Herunterfahren",
        restart: "Neu starten",
        sleep: "Energie sparen",
        password: "Kennwort",
        capsLock: "Die Feststelltaste ist aktiviert",
        networkWired: "Verbunden (kabelgebunden)",
        networkWifi: "Verbunden (WLAN)",
        networkNone: "Nicht verbunden"
    },
    "es": {
        welcome: "Bienvenido",
        onScreenKeyboard: "Teclado en pantalla",
        accessibility: "Accesibilidad",
        on: "Activado",
        off: "Desactivado",
        powerOptions: "Opciones de energía",
        shutdownDesc: "Cierra todas las aplicaciones\ny apaga el equipo.",
        restartDesc: "Cierra todas las aplicaciones,\napaga el equipo y vuelve a encenderlo.",
        sleepDesc: "El equipo permanece encendido pero consume poca energía.\nLas aplicaciones siguen abiertas, así que cuando el equipo\nse reactive, volverás al instante a donde lo dejaste.",
        pin: "PIN",
        submit: "Enviar",
        ok: "Aceptar",
        wrongPassword: "La contraseña no es correcta. Inténtalo de nuevo.",
        shutdown: "Apagar",
        restart: "Reiniciar",
        sleep: "Suspender",
        password: "Contraseña",
        capsLock: "Bloq Mayús está activado",
        networkWired: "Conectado (cable)",
        networkWifi: "Conectado (Wi-Fi)",
        networkNone: "Sin conexión"
    },
    "it": {
        welcome: "Benvenuto",
        onScreenKeyboard: "Tastiera su schermo",
        accessibility: "Accessibilità",
        on: "Attivato",
        off: "Disattivato",
        powerOptions: "Opzioni risparmio energia",
        shutdownDesc: "Chiude tutte le app\ne spegne il PC.",
        restartDesc: "Chiude tutte le app, spegne il PC\ne poi lo riaccende.",
        sleepDesc: "Il PC rimane acceso ma consuma poca energia.\nLe app rimangono aperte, così quando il PC si riattiva\nritrovi subito tutto come l'avevi lasciato.",
        pin: "PIN",
        submit: "Invia",
        ok: "OK",
        wrongPassword: "La password non è corretta. Riprova.",
        shutdown: "Arresta il sistema",
        restart: "Riavvia il sistema",
        sleep: "Sospendi",
        password: "Password",
        capsLock: "BLOC MAIUSC è attivo",
        networkWired: "Connesso (cablato)",
        networkWifi: "Connesso (Wi-Fi)",
        networkNone: "Nessuna connessione"
    },
    "pt": {
        welcome: "Bem-vindo",
        onScreenKeyboard: "Teclado virtual",
        accessibility: "Acessibilidade",
        on: "Ativado",
        off: "Desativado",
        powerOptions: "Opções de energia",
        shutdownDesc: "Fecha todos os aplicativos\ne desliga o PC.",
        restartDesc: "Fecha todos os aplicativos, desliga o PC\ne o liga novamente.",
        sleepDesc: "O PC permanece ligado, mas consome pouca energia.\nOs aplicativos continuam abertos para que, quando o PC\nfor ativado, você volte imediatamente de onde parou.",
        pin: "PIN",
        submit: "Enviar",
        ok: "OK",
        wrongPassword: "A senha está incorreta. Tente novamente.",
        shutdown: "Desligar",
        restart: "Reiniciar",
        sleep: "Suspender",
        password: "Senha",
        capsLock: "Caps Lock está ativado",
        networkWired: "Conectado (cabo)",
        networkWifi: "Conectado (Wi-Fi)",
        networkNone: "Sem conexão"
    },
    "nl": {
        welcome: "Welkom",
        onScreenKeyboard: "Schermtoetsenbord",
        accessibility: "Toegankelijkheid",
        on: "Aan",
        off: "Uit",
        powerOptions: "Opties voor energiebeheer",
        shutdownDesc: "Sluit alle apps af\nen zet de pc uit.",
        restartDesc: "Sluit alle apps af, zet de pc uit\nen zet deze daarna weer aan.",
        sleepDesc: "De pc blijft aan, maar verbruikt weinig energie.\nApps blijven geopend, zodat u bij het activeren\nvan de pc meteen verder kunt waar u was gebleven.",
        pin: "Pincode",
        submit: "Verzenden",
        ok: "OK",
        wrongPassword: "Het wachtwoord is onjuist. Probeer het opnieuw.",
        shutdown: "Afsluiten",
        restart: "Opnieuw opstarten",
        sleep: "Slaapstand",
        password: "Wachtwoord",
        capsLock: "Caps Lock is ingeschakeld",
        networkWired: "Verbonden (bekabeld)",
        networkWifi: "Verbonden (wifi)",
        networkNone: "Niet verbonden"
    },
    "pl": {
        welcome: "Witamy",
        onScreenKeyboard: "Klawiatura ekranowa",
        accessibility: "Ułatwienia dostępu",
        on: "Włączone",
        off: "Wyłączone",
        powerOptions: "Opcje zasilania",
        shutdownDesc: "Zamyka wszystkie aplikacje\ni wyłącza komputer.",
        restartDesc: "Zamyka wszystkie aplikacje, wyłącza komputer,\na następnie ponownie go włącza.",
        sleepDesc: "Komputer pozostaje włączony, ale zużywa mało energii.\nAplikacje pozostają otwarte, więc po wznowieniu pracy\nod razu wracasz do miejsca, w którym skończyłeś.",
        pin: "PIN",
        submit: "Prześlij",
        ok: "OK",
        wrongPassword: "Hasło jest niepoprawne. Spróbuj ponownie.",
        shutdown: "Zamknij",
        restart: "Uruchom ponownie",
        sleep: "Uśpij",
        password: "Hasło",
        capsLock: "Klawisz Caps Lock jest włączony",
        networkWired: "Połączono (przewodowo)",
        networkWifi: "Połączono (Wi-Fi)",
        networkNone: "Brak połączenia"
    },
    "ru": {
        welcome: "Добро пожаловать",
        onScreenKeyboard: "Экранная клавиатура",
        accessibility: "Специальные возможности",
        on: "Вкл.",
        off: "Откл.",
        powerOptions: "Параметры питания",
        shutdownDesc: "Закрывает все приложения\nи выключает компьютер.",
        restartDesc: "Закрывает все приложения, выключает\nкомпьютер, а затем снова включает его.",
        sleepDesc: "Компьютер остается включенным, но потребляет мало энергии.\nПриложения остаются открытыми, поэтому после выхода\nиз спящего режима вы сразу вернетесь к работе.",
        pin: "ПИН-код",
        submit: "Отправить",
        ok: "ОК",
        wrongPassword: "Неверный пароль. Повторите попытку.",
        shutdown: "Завершение работы",
        restart: "Перезагрузка",
        sleep: "Спящий режим",
        password: "Пароль",
        capsLock: "Включен Caps Lock",
        networkWired: "Подключено (проводная сеть)",
        networkWifi: "Подключено (Wi-Fi)",
        networkNone: "Нет подключения"
    },
    "tr": {
        welcome: "Hoş geldiniz",
        onScreenKeyboard: "Ekran klavyesi",
        accessibility: "Erişilebilirlik",
        on: "Açık",
        off: "Kapalı",
        powerOptions: "Güç seçenekleri",
        shutdownDesc: "Tüm uygulamaları kapatır\nve bilgisayarı kapatır.",
        restartDesc: "Tüm uygulamaları kapatır, bilgisayarı kapatır\nve ardından yeniden açar.",
        sleepDesc: "Bilgisayar açık kalır ancak az güç kullanır.\nUygulamalar açık kalır; böylece bilgisayar uyandığında\nkaldığınız yere anında dönersiniz.",
        pin: "PIN",
        submit: "Gönder",
        ok: "Tamam",
        wrongPassword: "Parola yanlış. Yeniden deneyin.",
        shutdown: "Kapat",
        restart: "Yeniden başlat",
        sleep: "Uyku",
        password: "Parola",
        capsLock: "Caps Lock açık",
        networkWired: "Bağlı (kablolu)",
        networkWifi: "Bağlı (Wi-Fi)",
        networkNone: "Bağlantı yok"
    },
    "ja": {
        welcome: "ようこそ",
        onScreenKeyboard: "スクリーン キーボード",
        accessibility: "アクセシビリティ",
        on: "オン",
        off: "オフ",
        powerOptions: "電源オプション",
        shutdownDesc: "すべてのアプリを閉じて\nPC の電源を切ります。",
        restartDesc: "すべてのアプリを閉じて PC の電源を切り、\nその後もう一度電源を入れます。",
        sleepDesc: "PC の電源は入ったままですが、消費電力は少なくなります。\nアプリは開いたままなので、PC がスリープから復帰すると\n中断したところからすぐに再開できます。",
        pin: "PIN",
        submit: "送信",
        ok: "OK",
        wrongPassword: "パスワードが正しくありません。もう一度やり直してください。",
        shutdown: "シャットダウン",
        restart: "再起動",
        sleep: "スリープ",
        password: "パスワード",
        capsLock: "Caps Lock がオンになっています",
        networkWired: "接続済み (有線)",
        networkWifi: "接続済み (Wi-Fi)",
        networkNone: "接続されていません"
    },
    "zh": {
        welcome: "欢迎",
        onScreenKeyboard: "屏幕键盘",
        accessibility: "辅助功能",
        on: "开",
        off: "关",
        powerOptions: "电源选项",
        shutdownDesc: "关闭所有应用\n并关闭电脑。",
        restartDesc: "关闭所有应用，关闭电脑，\n然后重新打开电脑。",
        sleepDesc: "电脑保持开启状态，但耗电量很低。\n应用会保持打开状态，因此电脑唤醒后，\n你可以立即回到离开时的位置。",
        pin: "PIN",
        submit: "提交",
        ok: "确定",
        wrongPassword: "密码不正确。请再试一次。",
        shutdown: "关机",
        restart: "重启",
        sleep: "睡眠",
        password: "密码",
        capsLock: "大写锁定已打开",
        networkWired: "已连接（有线）",
        networkWifi: "已连接（WLAN）",
        networkNone: "未连接"
    }
}

// System language code: "fr_FR" -> "fr_FR" if available, else "fr", else "en".
function langue() {
    var nom = Qt.locale().name
    if (texts[nom] !== undefined)
        return nom
    var court = nom.split("_")[0]
    if (texts[court] !== undefined)
        return court
    return "en"
}

// Returns the text for a key in the system language (English as fallback).
function t(cle) {
    var l = langue()
    if (texts[l][cle] !== undefined)
        return texts[l][cle]
    return texts["en"][cle]
}
